apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus
  labels:
    app: quarkus
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
        - name: quarkus
          image: pavolloffay/code-with-quarkus-jvm-opentracing-example:latest
          ports:
            - containerPort: 8080
